### ISSUE TITLE
IPv4 Contextualization not working

### ISSUE THREAD

**Issue by iandk** [OpenNebula/addon-context-windows#41] opened 2018-05-21 20:36 UTC
Hi, 

I just created a Windows Server 2016 image as described in the wiki. 
The IPv6 contextualization is working without a problem, but unfortunately on the IPv4 side it isn't working, only the Gateway has been added. 

IPv4 NIC Settings:
![rhfsil7](https://user-images.githubusercontent.com/13487247/40328474-cd0b12f0-5d46-11e8-8ee5-47fb061d8531.png)

I tried to enter the values manually and noticed the appereance of a message that the IP and Gateway are in different subnets. I had to manually click ok and after that it also works.
Maybe that's where the problem is located?

![7owxobv](https://user-images.githubusercontent.com/13487247/40328591-30874592-5d47-11e8-9cc5-114e753b120f.png)

**Comment by vholer** [comment] 2018-06-18 16:04
I'm trying to reproduce the problem, but on my W2016, I'm able to statically configure even the interface with the gateway outside the subnet (what I don't understand is the meaning of such configuration).

Can you please check the contextualization log in `C:\.opennebula-context.out`, maybe you'll see an error code near the **Enable Static IP** log message. Can you please check if the generated context (`D:\context.sh`) contains your desired IPv4 configuration? Thank you.

**Comment by vholer** [comment] 2020-02-17 09:21
As we can't reproduce the issue and nobody else complained, closing.

**Closed by vholer** 2020-02-17 09:21 UTC
Labels: Status: Accepted, Type: Bug
